# Generated by Django 4.1.13 on 2024-11-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_email', models.TextField()),
                ('email_type', models.CharField(max_length=50)),
                ('tone', models.CharField(max_length=50)),
                ('generated_subject', models.CharField(max_length=255)),
                ('generated_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
